# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5059960195ac37c566587e0262d0e18a9b3a002e186f0153f7ed9fe8c4ff4da40577230ecac3f2c065f9cc30b68293bbdbf112aaf404774bfbf08404743e8545

test:
  secret_key_base: 668704824259fa57076b1f1e30d88445b1ec71c348e72829e8b4ab20778cc62ae8f770573171eb89170fcda431e8547e606bb76e70eebedabca39fa037b19f56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
